Repository michal367/OI-Project, pull requests merged in 2021-06, with the labels that each got.

#340 enable PWA for student app (#332)(#333)
  config-overrides.js
  package.json
  public/index.html
  public/lecturer/favicon.ico
  public/lecturer/index.html
  public/lecturer/logo192.png
  public/lecturer/manifest.json
  public/lecturer/panel512.png
  public/lecturer/robots.txt
  public/student/favicon.ico
  public/student/index.html
  public/student/logo192.png
  public/student/manifest.json
  public/student/panel512.png
  public/student/robots.txt
  src/lecturer/components/app/App.tsx
  src/lecturer/service-worker.ts
  src/lecturer/serviceWorkerRegistration.ts
  src/student/components/app/App.tsx
  src/student/index.tsx
  src/student/service-worker.ts
  src/student/serviceWorkerRegistration.ts
Labels: enhancement, lecturerapp, studentapp, toolsengineer

#271 Send quiz functionality
  package-lock.json
  server/Lecture.ts
  server/Student.ts
  src/@types/types.d.ts
  src/common/util/time.ts
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/listView/ListView.tsx
  src/lecturer/components/questionsListView/QuestionsListView.tsx
  src/lecturer/components/quizStatsView/QuizStatsView.tsx
  src/lecturer/components/quizzesListView/QuizzesListView.tsx
  src/lecturer/components/reactionReceiveView/ReactionCounter.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/sendQuizView/QuizListView.tsx
  src/lecturer/components/sendQuizView/SendQuizView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/components/studentListView/StudentListView.tsx
  src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
  src/lecturer/services/StoreService.tsx
  src/lecturer/util/mock/data.ts
  src/student/components/quizView/Answer.tsx
  src/student/components/quizView/Option.tsx
  src/student/components/quizView/QuestionsList.tsx
  src/student/components/quizView/QuizView.tsx
  src/student/components/sessionDashboardView/SessionDashboardView.tsx
  src/student/components/timerClock/timerClock.tsx
  src/student/services/StoreService.tsx
Labels: bug

#364 improve clicked reaction aniamtion
  server/Student.ts
  src/common/util/config.ts
  src/common/util/globalConfig.ts
  src/student/components/sendQuestionView/SendQuestion.tsx
  src/student/components/sessionReactionView/ReactionItem.tsx
  src/student/components/sessionReactionView/SessionReactionView.tsx
Labels: front

#363 add IDs to objects (#295)
  package-lock.json
  package.json
  src/@types/types.d.ts
  src/lecturer/components/createQuestionView/CreateQuestionView.tsx
  src/lecturer/components/createQuizView/CreateQuizView.tsx
  src/lecturer/components/questionsListView/QuestionsListView.tsx
  src/lecturer/services/StoreService.tsx
  src/lecturer/util/mock/data.ts
  src/lecturer/util/mock/includeMockData.ts
Labels: enhancement, front

#369 Feature/better animation student reaction
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/quizStatsView/QuestionBlock.tsx
  src/lecturer/components/quizStatsView/QuizStatsView.tsx
  src/student/components/feedbackView/FeedbackView.tsx
  src/student/components/quizView/QuestionsList.tsx
  src/student/services/StoreService.tsx
Labels: front, lecturerapp, studentapp

#370 quizzes preview and edit (#297)
  src/lecturer/components/createQuestionView/CreateQuestionView.tsx
  src/lecturer/components/createQuizView/CreateQuizView.tsx
  src/lecturer/components/listView/ListView.tsx
Labels: front

#367 Lecturer and student reconnection
  server/Lecture.ts
  server/Student.ts
  server/websockets.ts
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createQuizView/CreateQuizView.tsx
  src/lecturer/services/SocketService.tsx
  src/student/components/app/App.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
  src/student/index.tsx
  src/student/services/SocketService.tsx
  src/student/services/StoreService.tsx
Labels: back, bug, front, lecturerapp, studentapp

#371 Refactor/lecturer listeners
  src/@types/types.d.ts
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createQuestionView/CreateQuestionView.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
  src/lecturer/components/topBar/NotifiableTab.tsx
  src/lecturer/components/topBar/topBar.tsx
  src/lecturer/index.tsx
Labels: bug, front, lecturerapp
