Repository michal367/OI-Project, pull requests merged in 2021-05, with the labels that each got.

#163 back api for student reactions
  server/@types/payloads/types.d.ts
  server/Lecture.ts
  server/Student.ts
  server/StudentList.ts
  server/api/websocket-api.md
Labels: back

#171 Feature/filter questions
  src/lecturer/components/pickQuizView/PickQuizView.tsx
  src/lecturer/components/questionsListView/QuestionsListView.tsx
Labels: front

#173 Feature/new inputs in session joining (#75) (#168)
  src/lecturer/components/studentListView/StudentListView.tsx
  src/lecturer/services/StoreService.tsx
  src/student/components/app/App.tsx
  src/student/components/chooseNicknameView/ChooseNicknameView.tsx
  src/student/components/joinSessionView/JoinSessionView.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
  src/student/services/BackEndService.tsx
  src/student/services/StoreService.tsx
Labels: front

#175 Feature/share session view
  package-lock.json
  package.json
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/components/shareSessionView/CopyLinkForm.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/components/studentListView/CopyLinkButton.tsx
  src/lecturer/components/topBar/topBar.tsx
  src/student/services/BackEndService.tsx
Labels: enhancement, front

#188 fix - send quiz time to student
  server/@types/payloads/types.d.ts
  server/Lecture.ts
  server/api/websocket-api.md
Labels: bug

#201 fix respo (#200)
  src/student/components/quizView/QuestionsList.tsx
  src/student/components/quizView/QuizView.tsx
  src/student/components/sendQuestionView/SendQuestion.tsx
  src/student/components/sessionDashboardView/SessionDashboardView.tsx
  src/student/components/sessionDetailsView/SessionDetailsView.tsx
Labels: enhancement, front

#196 Feature - student anon question
  server/@types/payloads/types.d.ts
  server/Lecture.ts
  server/Student.ts
  server/api/websocket-api.md
Labels: back

#195 Feature - show students' correct quiz answers
  .gitignore
  package-lock.json
  server/@types/frontTypes.d.ts
  server/@types/payloads/types.d.ts
  server/Lecture.ts
  server/Quiz.ts
  server/api/websocket-api.md
  server/server.ts
Labels: back

#204 deno http server (#203)
  package.json
  server/routes.ts
  server/server.ts
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/questionsListView/QuestionsListView.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/components/topBar/topBar.tsx
  src/student/components/app/App.tsx
  src/student/components/joinSessionView/JoinSessionView.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
Labels: back, enhancement

#212 Feature/icon
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/panel512.png
Labels: enhancement, front

#210 Add reaction indicator for lecturer (#107)
  package-lock.json
  src/lecturer/components/reactionReceiveView/ReactionCounter.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/services/StoreService.tsx
  src/lecturer/util/reactionsEnum.tsx
  src/student/components/sessionDashboardView/SessionDashboardView.tsx
  src/student/components/sessionReactionView/ReactionItem.tsx
  src/student/components/sessionReactionView/SessionReactionView.tsx
  src/student/util/reactionsEnum.tsx
Labels: front

#269 unify types and fix some warnings (#223)
  server/@types/frontTypes.d.ts
  server/@types/payloads/types.d.ts
  server/@types/serverTypes.ts
  server/@types/types.ts
  server/Lecture.ts
  server/Student.ts
  server/StudentList.ts
  server/routes.ts
  server/server.ts
  server/websockets.ts
  src/@types/serverTypes.d.ts
  src/@types/types.d.ts
  src/lecturer/components/quizStatsView/QuizStatsView.tsx
  src/lecturer/components/reactionReceiveView/ReactionCounter.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/sendQuizView/QuizListView.tsx
  src/lecturer/components/sendQuizView/SendQuizView.tsx
  src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
  src/lecturer/services/StoreService.tsx
  src/lecturer/util/mockData.ts
  src/student/components/feedbackView/FeedbackView.tsx
  src/student/services/StoreService.tsx
Labels: back, front

#270 Feature/fix stats layout
  src/@types/types.d.ts
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createQuestionView/CreateQuestionView.tsx
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/notifiableTab/NotifiableTab.tsx
  src/lecturer/components/pickQuizView/PickQuizList.tsx
  src/lecturer/components/pickQuizView/PickQuizView.tsx
  src/lecturer/components/questionsListView/QuestionsListView.tsx
  src/lecturer/components/quizStatsView/AnswerBar.tsx
  src/lecturer/components/quizStatsView/QuestionBlock.tsx
  src/lecturer/components/quizStatsView/QuizStatsView.tsx
  src/lecturer/components/quizStatsView/testData.tsx
  src/lecturer/components/sendQuizView/QuizListView.tsx
  src/lecturer/components/sendQuizView/SendQuizView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/components/studentListView/StudentListView.tsx
  src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
  src/lecturer/components/topBar/topBar.tsx
  src/lecturer/services/StoreService.tsx
  src/lecturer/util/mockData.ts
Labels: enhancement, front

#282 Fix/code input wont dissapear
  server/@types/frontTypes.d.ts
  server/@types/payloads/types.d.ts
  server/@types/serverTypes.ts
  server/@types/types.ts
  server/Lecture.ts
  server/Student.ts
  server/StudentList.ts
  server/routes.ts
  server/server.ts
  server/websockets.ts
  src/@types/serverTypes.d.ts
  src/@types/types.d.ts
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createQuestionView/CreateQuestionView.tsx
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/notifiableTab/NotifiableTab.tsx
  src/lecturer/components/pickQuizView/PickQuizList.tsx
  src/lecturer/components/pickQuizView/PickQuizView.tsx
  src/lecturer/components/questionsListView/QuestionsListView.tsx
  src/lecturer/components/quizStatsView/AnswerBar.tsx
  src/lecturer/components/quizStatsView/QuestionBlock.tsx
  src/lecturer/components/quizStatsView/QuizStatsView.tsx
  src/lecturer/components/quizStatsView/testData.tsx
  src/lecturer/components/reactionReceiveView/ReactionCounter.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/sendQuizView/QuizListView.tsx
  src/lecturer/components/sendQuizView/SendQuizView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/components/studentListView/StudentListView.tsx
  src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
  src/lecturer/components/topBar/topBar.tsx
  src/lecturer/components/uploadImageField/uploadImageField.tsx
  src/lecturer/services/StoreService.tsx
  src/lecturer/util/mockData.ts
  src/student/components/app/App.tsx
  src/student/components/feedbackView/FeedbackView.tsx
  src/student/components/joinSessionView/JoinSessionView.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
  src/student/services/StoreService.tsx
Labels: bug, enhancement

#283 add images for questions view (#221)
  src/lecturer/components/uploadImageField/uploadImageField.tsx
  src/student/components/feedbackView/FeedbackView.tsx
  src/student/components/quizView/QuestionsList.tsx
  src/student/components/quizView/imageView.tsx
  src/student/components/quizView/testData.tsx
  src/student/components/sessionDashboardView/SessionDashboardView.tsx
Labels: front

#277 Send student reaction functionality
  server/Lecture.ts
  server/Student.ts
  src/@types/serverTypes.d.ts
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/services/BackEndService.tsx
  src/student/components/sessionReactionView/SessionReactionView.tsx
Labels: back, front

#275 Send student question functionality
  config-overrides.js
  package-lock.json
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
  src/lecturer/index.tsx
  src/lecturer/services/BackEndService.tsx
  src/lecturer/services/SocketService.tsx
  src/lecturer/util/GenericContext.ts
  src/student/components/app/App.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
  src/student/components/sendQuestionView/SendQuestion.tsx
  src/student/components/sessionReactionView/SessionReactionView.tsx
  src/student/index.tsx
  src/student/services/BackEndService.tsx
  src/student/services/SocketService.tsx
  src/student/util/GenericContext.ts
Labels: bug

#285 seperate import/export functionality to component (#242)
  src/lecturer/components/importExport/ImportExport.tsx
  src/lecturer/components/questionsListView/QuestionsListView.tsx
  src/lecturer/components/quizStatsView/AnswerBar.tsx
  src/lecturer/components/quizStatsView/QuestionBlock.tsx
  src/lecturer/components/quizStatsView/QuizStatsView.tsx
  src/lecturer/services/FileService.tsx
Labels: front

#302 add timer to quiz view (#293)
  src/student/components/app/App.tsx
  src/student/components/quizView/QuestionsList.tsx
  src/student/components/sendQuestionView/SendQuestion.tsx
  src/student/components/sessionDashboardView/SessionDashboardView.tsx
  src/student/components/timerClock/timerClock.tsx
  src/student/util/time.ts
Labels: front

#301 Feature/student disconnect
  package-lock.json
  src/student/components/app/App.tsx
  src/student/components/joinSessionView/JoinSessionView.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
  src/student/components/sessionDashboardView/SessionDashboardView.tsx
  src/student/components/sessionDetailsView/SessionDetailsView.tsx
  src/student/services/SocketService.tsx
  src/student/services/StoreService.tsx
Labels: front

#303 Feature/shared module reactions
  config-overrides.js
  src/common/util/GenericContext.ts
  src/common/util/boolAlgebra.ts
  src/common/util/comparators.ts
  src/common/util/config.ts
  src/common/util/mockData.ts
  src/common/util/random.ts
  src/common/util/reactions/enum.ts
  src/common/util/reactions/icons.tsx
  src/common/util/time.ts
  src/lecturer/components/pickQuizView/PickQuizView.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/sendQuizView/SendQuizView.tsx
  src/lecturer/components/studentListView/StudentListHead.tsx
  src/lecturer/components/studentListView/StudentListView.tsx
  src/lecturer/components/timestampView/TimestampRow.tsx
  src/lecturer/components/timestampView/TimestampTable.tsx
  src/lecturer/components/topBar/topBar.tsx
  src/lecturer/services/SocketService.tsx
  src/lecturer/services/StoreService.tsx
  src/student/components/sessionDashboardView/SessionDashboardView.tsx
  src/student/components/sessionReactionView/ReactionItem.tsx
  src/student/components/sessionReactionView/SessionReactionView.tsx
  src/student/components/timerClock/timerClock.tsx
  src/student/services/SocketService.tsx
  src/student/util/GenericContext.ts
  src/student/util/reactionsEnum.tsx
  src/student/util/time.ts
Labels: back, front

#185 Migrate from rest to full websocket
  server/Lecture.ts
  server/Student.ts
  server/StudentList.ts
  server/api/lecture.md
  server/api/server-api.md
  server/api/student.md
  server/controllers/lectures.ts
  server/routes.ts
  server/server.ts
  server/websockets.ts
  src/@types/serverTypes.d.ts
  src/@types/types.d.ts
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/services/BackEndService.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
  src/student/services/StoreService.tsx
Labels: back

#338 add versioning to local storage and move code to common (#315)
  src/common/util/LazareLocalStorage.ts
  src/common/util/config.ts
  src/lecturer/services/StoreService.tsx
  src/student/services/StoreService.tsx
Labels: front

#341 bugfixes and enhancements (#258)(#318)(#320)(#322)(#323)
  server/Student.ts
  src/lecturer/components/importExport/ImportExport.tsx
  src/lecturer/components/sendQuizView/SendQuizView.tsx
  src/lecturer/components/shareSessionView/CopyLinkForm.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/components/timestampView/TimestampRow.tsx
  src/lecturer/components/timestampView/TimestampTable.tsx
  src/lecturer/components/timestampView/TimestampView.tsx
  src/student/components/sendQuestionView/SendQuestion.tsx
Labels: bug, enhancement

#339 make delete button circular on hover and add back button (#324)(#279)
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createQuestionView/CreateQuestionView.tsx
  src/lecturer/components/createQuizView/CreateQuizList.tsx
  src/lecturer/components/createQuizView/CreateQuizView.tsx
  src/lecturer/components/listView/ListView.tsx
Labels: front

#337 Fix/store session and visual bug + reaction final features
  package-lock.json
  server/server.ts
  src/common/util/LazareLocalStorage.ts
  src/lecturer/components/app/App.tsx
  src/lecturer/components/createSessionView/CreateSessionView.tsx
  src/lecturer/components/quizStatsView/QuizStatsView.tsx
  src/lecturer/components/reactionReceiveView/ReactionCounter.tsx
  src/lecturer/components/reactionReceiveView/ReactionProgress.tsx
  src/lecturer/components/reactionReceiveView/ReactionReceiveView.tsx
  src/lecturer/components/sendQuizView/SendQuizView.tsx
  src/lecturer/components/sessionDashboardView/SessionDashboardView.tsx
  src/lecturer/components/shareSessionView/ShareSessionView.tsx
  src/lecturer/components/studentListView/StudentListView.tsx
  src/lecturer/components/studentsQuestionView/StudentsQuestionListView.tsx
  src/lecturer/components/timestampView/TimestampTable.tsx
  src/lecturer/components/timestampView/TimestampView.tsx
  src/lecturer/components/topBar/NotifiableTab.tsx
  src/lecturer/components/topBar/topBar.tsx
  src/lecturer/services/BackEndService.tsx
  src/lecturer/services/StoreService.tsx
  src/lecturer/util/mock/data.ts
  src/lecturer/util/mock/includeMockData.ts
  src/lecturer/util/route/routeToTabsValue.ts
  src/student/components/joinSessionView/JoinSessionView.tsx
  src/student/components/joinSessionView/StudentFormView.tsx
  src/student/components/quizView/QuestionsList.tsx
Labels: back, bug, enhancement, front, lecturerapp, studentapp
